=== ytz3210/ocr/src/main/resources/static/api-standard.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- 简易元素的定义 -->
    <xs:element name="img"  type="xs:string"/>
    <xs:element name="td" type="xs:string"/>
    <xs:element name="name" type="xs:string"/>
    <!-- 属性的定义 -->
    <xs:attribute name="orderid" type="xs:string"/>

    <!-- 复合元素的定义 -->
    <xs:element name="title">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="name"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="img"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="table"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="second-title"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="second-title">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="third-title" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="img" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="table" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="third-title">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="img" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="table" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tr" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tr">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="td"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="body">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ytz3210/ocr/src/main/resources/static/api.xml
<?xml version="1.0" encoding="UTF-8" ?>
<body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="api-standard.xsd">
    <title>
        <name>1.文件上传</name>
        <second-title>
            <name>1.1请求地址</name>
            <table>
                <tr>
                    <td>操作</td>
                    <td>协议</td>
                    <td>方式</td>
                    <td>网址全径</td>
                </tr>
                <tr>
                    <td>parseForm</td>
                    <td>HTTP</td>
                    <td>POST</td>
                    <td>/API/parseForm</td>
                </tr>
            </table>
        </second-title>
        <second-title>
            <name>1.2请求参数</name>
            <table>
                <tr>
                    <td>参数名</td>
                    <td>必填</td>
                    <td>字段类型</td>
                    <td>描述</td>
                </tr>
                <tr>
                    <td>file</td>
                    <td>是</td>
                    <td>文件</td>
                    <td>文件包含的数据文件（最大文件10MB）</td>
                </tr>
            </table>
        </second-title>
        <second-title>
            <name>1.3返回数据</name>
            <table>
                <tr>
                    <td>序号</td>
                    <td>返回值</td>
                    <td>中文名称</td>
                    <td>备注</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>status</td>
                    <td>请求状态码</td>
                    <td>0表示成功
                        非0表示失败
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>data</td>
                    <td>返回数据</td>
                    <td>JSON数据，返回用户请求的数据</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>errorMessage</td>
                    <td>错误信息</td>
                    <td>可选信息，只有发生错误时才返回，装载发生错误的具体信息</td>
                </tr>
            </table>
        </second-title>
        <second-title>
            <name>1.4字段含义</name>
            <table>
                <tr>
                    <td>字段名称</td>
                    <td>字段含义</td>
                </tr>
                <tr>
                    <td>shipCompany</td>
                    <td>船公司</td>
                </tr>
                <tr>
                    <td>bookingNo</td>
                    <td>提单号</td>
                </tr>
                <tr>
                    <td>bargeShipName</td>
                    <td>驳船船名</td>
                </tr>
                <tr>
                    <td>bargeLine</td>
                    <td>驳船航次</td>
                </tr>
                <tr>
                    <td>shipName</td>
                    <td>船名</td>
                </tr>
                <tr>
                    <td>line</td>
                    <td>航次</td>
                </tr>
                <tr>
                    <td>bargeFrom</td>
                    <td>驳船起运港</td>
                </tr>
                <tr>
                    <td>from</td>
                    <td>起运港</td>
                </tr>
                <tr>
                    <td>to</td>
                    <td>卸货港</td>
                </tr>
                <tr>
                    <td>delivery</td>
                    <td>交货地</td>
                </tr>
                <tr>
                    <td>boxInfos</td>
                    <td>type：箱型</td>
                </tr>
                <tr>
                    <td>boxInfos</td>
                    <td>quality：箱量</td>
                </tr>
                <tr>
                    <td>portCutOff</td>
                    <td>截关时间</td>
                </tr>
                <tr>
                    <td>etd</td>
                    <td>开航时间</td>
                </tr>
                <tr>
                    <td>bargeEtd</td>
                    <td>驳船开航时间</td>
                </tr>
                <tr>
                    <td>orderCutOff</td>
                    <td>截单时间</td>
                </tr>
                <tr>
                    <td>eta</td>
                    <td>到港时间</td>
                </tr>
                <tr>
                    <td>bargeEta</td>
                    <td>驳船到港时间</td>
                </tr>
            </table>
        </second-title>
        <second-title>
            <name>1.5请求URL实例</name>
            <img>/images/api-upload01.jpg</img>
        </second-title>
        <second-title>
            <name>1.6返回数据实例</name>
            <third-title>
                <name>1.6.1成功返回</name>
                <img>/images/api-upload02.jpg</img>
            </third-title>
            <third-title>
                <name>1.6.2失败返回</name>
                <img>/images/api-upload03.jpg</img>
            </third-title>
        </second-title>
    </title>
</body>
